-- Los precios ya no se seedearon con mock data.
-- Fuente operativa: importador Valor Agro en web/lib/valor-agro-prices.ts
-- Endpoint: /api/prices/valor-agro/run
-- El importador reemplaza market_prices completo con las referencias publicadas por Valor Agro.
