import type {
  NewsArticle,
  CattlePrice,
  InternationalPrice,
  EcosystemSite,
  InstitutionNews,
  Organization,
  MarketPrice,
  VideoItem,
  Profession,
  Department,
  NewsCategory
} from './types';

// Professions list
export const professions: { value: Profession; label: string }[] = [
  { value: 'productor', label: 'Productor/a' },
  { value: 'comunicador', label: 'Comunicador/a' },
  { value: 'veterinario', label: 'Veterinario/a' },
  { value: 'agronomo', label: 'Ingeniero/a Agronomo/a' },
  { value: 'comerciante', label: 'Comerciante' },
  { value: 'transportista', label: 'Transportista' },
  { value: 'estudiante', label: 'Estudiante' },
  { value: 'otro', label: 'Otro' },
];

// Departments list
export const departments: { value: Department; label: string }[] = [
  { value: 'asuncion', label: 'Asuncion' },
  { value: 'central', label: 'Central' },
  { value: 'alto-parana', label: 'Alto Parana' },
  { value: 'itapua', label: 'Itapua' },
  { value: 'caaguazu', label: 'Caaguazu' },
  { value: 'san-pedro', label: 'San Pedro' },
  { value: 'canindeyu', label: 'Canindeyu' },
  { value: 'paraguari', label: 'Paraguari' },
  { value: 'cordillera', label: 'Cordillera' },
  { value: 'guaira', label: 'Guaira' },
  { value: 'caazapa', label: 'Caazapa' },
  { value: 'misiones', label: 'Misiones' },
  { value: 'neembucu', label: 'Neembucu' },
  { value: 'amambay', label: 'Amambay' },
  { value: 'concepcion', label: 'Concepcion' },
  { value: 'presidente-hayes', label: 'Presidente Hayes' },
  { value: 'boqueron', label: 'Boqueron' },
  { value: 'alto-paraguay', label: 'Alto Paraguay' },
];

// News categories
export const newsCategories: { value: NewsCategory; label: string; icon: string }[] = [
  { value: 'ganaderia', label: 'Ganaderia', icon: 'cow' },
  { value: 'agricultura', label: 'Agricultura', icon: 'wheat' },
  { value: 'clima', label: 'Clima', icon: 'cloud-sun' },
  { value: 'mercados', label: 'Mercados', icon: 'trending-up' },
  { value: 'tecnologia', label: 'Tecnologia Agro', icon: 'cpu' },
  { value: 'institucional', label: 'Institucional', icon: 'building' },
];

// Organizations / cuentas verificadas
export const mockOrganizations: Organization[] = [
  { id: 'poder-agropecuario', name: 'Poder Agropecuario', description: 'Medio especializado en noticias y analisis del sector agropecuario paraguayo.', isVerified: true, category: 'media', commercialStatus: 'active', planName: 'Medio aliado' },
  { id: 'campo-agropecuario', name: 'Campo Agropecuario', description: 'El referente digital del campo paraguayo con cobertura nacional.', isVerified: true, category: 'media', commercialStatus: 'active', planName: 'Medio aliado' },
  { id: 'agroconecta-medios', name: 'Agroconecta Medios', description: 'Noticias, analisis y tendencias del agro desde el ecosistema Agroconecta.', isVerified: true, category: 'media', commercialStatus: 'active', planName: 'Interno' },
  { id: 'abc-rural', name: 'ABC Rural', description: 'Seccion agropecuaria de ABC Color, el diario de mayor circulacion del pais.', isVerified: true, category: 'media', commercialStatus: 'trial', planName: 'Piloto' },
  { id: 'asociacion-brangus', name: 'Asociacion Paraguaya de Brangus', description: 'Comunicados, remates, jornadas tecnicas y novedades oficiales de la raza Brangus.', isVerified: true, category: 'asociacion', commercialStatus: 'active', planName: 'Asociacion Pro' },
  { id: 'arp', name: 'Asociacion Rural del Paraguay', description: 'Gremio referente de la produccion ganadera y exposiciones rurales del Paraguay.', isVerified: true, category: 'gremio', commercialStatus: 'active', planName: 'Institucional' },
  { id: 'senacsa', name: 'SENACSA', description: 'Servicio Nacional de Calidad y Salud Animal. Organismo oficial del Estado.', isVerified: true, category: 'institucion', commercialStatus: 'active', planName: 'Institucional' },
  { id: 'mag', name: 'MAG', description: 'Ministerio de Agricultura y Ganaderia de la Republica del Paraguay.', isVerified: true, category: 'institucion', commercialStatus: 'active', planName: 'Institucional' },
  { id: 'senave', name: 'SENAVE', description: 'Servicio Nacional de Calidad y Sanidad Vegetal y de Semillas.', isVerified: true, category: 'institucion', commercialStatus: 'active', planName: 'Institucional' },
  { id: 'remates-paraguay', name: 'Remates Paraguay', description: 'Agenda y transmision de remates ganaderos en vivo desde todo el pais.', isVerified: true, category: 'rematadora', commercialStatus: 'trial', planName: 'Remates' },
];

export const mockPublishers = mockOrganizations;

// Mock News
export const mockNews: NewsArticle[] = [
  {
    id: '1',
    title: 'Paraguay registra record historico en exportacion de carne bovina',
    summary: 'El pais alcanzo cifras sin precedentes en el primer trimestre del 2026, consolidandose como uno de los principales exportadores de la region.',
    content: 'El sector ganadero paraguayo continua su expansion...',
    category: 'ganaderia',
    imageUrl: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=800',
    source: 'Agroconecta Medios',
    organizationId: 'agroconecta-medios',
    publisherId: 'agroconecta-medios',
    contentType: 'article',
    editorialStatus: 'published',
    isImportant: true,
    publishedAt: new Date('2026-05-06'),
    readTime: 4,
    isHighlighted: true,
  },
  {
    id: '2',
    title: 'Soja: Precios internacionales muestran tendencia alcista',
    summary: 'Chicago registra aumentos significativos impulsados por la demanda asiatica y condiciones climaticas adversas en Brasil.',
    content: 'Los futuros de soja en el mercado de Chicago...',
    category: 'mercados',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800',
    source: 'Campo Agropecuario',
    organizationId: 'campo-agropecuario',
    publisherId: 'campo-agropecuario',
    contentType: 'article',
    editorialStatus: 'published',
    isImportant: false,
    publishedAt: new Date('2026-05-06'),
    readTime: 3,
  },
  {
    id: '3',
    title: 'Alerta climatica: Pronostican lluvias intensas para la region Oriental',
    summary: 'El Servicio Meteorologico Nacional advierte sobre precipitaciones abundantes para los proximos dias.',
    content: 'Las condiciones meteorologicas indican...',
    category: 'clima',
    imageUrl: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=800',
    source: 'Poder Agropecuario',
    organizationId: 'poder-agropecuario',
    publisherId: 'poder-agropecuario',
    contentType: 'article',
    editorialStatus: 'published',
    isImportant: true,
    publishedAt: new Date('2026-05-05'),
    readTime: 2,
  },
  {
    id: '4',
    title: 'Nueva tecnologia de riego inteligente llega a Paraguay',
    summary: 'Sistemas de precision que permiten ahorrar hasta un 40% de agua estan siendo implementados en el Chaco.',
    content: 'La agricultura de precision avanza en Paraguay...',
    category: 'tecnologia',
    imageUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800',
    source: 'ABC Rural',
    organizationId: 'abc-rural',
    publisherId: 'abc-rural',
    contentType: 'article',
    editorialStatus: 'published',
    isImportant: false,
    publishedAt: new Date('2026-05-05'),
    readTime: 5,
  },
  {
    id: '5',
    title: 'Zafrina de maiz: Expectativas superan los 5 millones de toneladas',
    summary: 'Los productores mantienen optimismo pese a los desafios climaticos de la temporada.',
    content: 'La campana de maiz zafrina avanza con buenos numeros...',
    category: 'agricultura',
    imageUrl: 'https://images.unsplash.com/photo-1601472544834-5ec4b49d0a4c?w=800',
    source: 'Campo Agropecuario',
    organizationId: 'campo-agropecuario',
    publisherId: 'campo-agropecuario',
    contentType: 'article',
    editorialStatus: 'published',
    isImportant: false,
    publishedAt: new Date('2026-05-04'),
    readTime: 4,
  },
  {
    id: '6',
    title: 'SENACSA habilita nuevos frigorificos para exportacion a la UE',
    summary: 'Tres establecimientos mas cumplen con los estandares requeridos por el mercado europeo.',
    content: 'El Servicio Nacional de Calidad y Salud Animal...',
    category: 'institucional',
    imageUrl: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800',
    source: 'SENACSA',
    organizationId: 'senacsa',
    publisherId: 'senacsa',
    contentType: 'institutional_notice',
    editorialStatus: 'published',
    isImportant: true,
    publishedAt: new Date('2026-05-04'),
    readTime: 3,
  },
  {
    id: '7',
    title: 'Ganaderia regenerativa: El futuro sostenible del Chaco paraguayo',
    summary: 'Productores adoptan practicas que mejoran la productividad y cuidan el medio ambiente.',
    content: 'La ganaderia regenerativa esta ganando terreno...',
    category: 'ganaderia',
    imageUrl: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800',
    source: 'Poder Agropecuario',
    organizationId: 'asociacion-brangus',
    publisherId: 'poder-agropecuario',
    contentType: 'article',
    editorialStatus: 'published',
    isImportant: false,
    publishedAt: new Date('2026-05-03'),
    readTime: 6,
  },
  {
    id: '8',
    title: 'Trigo: Productores se preparan para la siembra de invierno',
    summary: 'Las condiciones del suelo son favorables para iniciar la campana triguera 2026.',
    content: 'Con la finalizacion de la zafrina...',
    category: 'agricultura',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800',
    source: 'ABC Rural',
    organizationId: 'abc-rural',
    publisherId: 'abc-rural',
    contentType: 'article',
    editorialStatus: 'published',
    isImportant: false,
    publishedAt: new Date('2026-05-03'),
    readTime: 3,
  },
];

// Mock Cattle Prices
export const mockCattlePrices: CattlePrice[] = [
  { id: '1', category: 'Novillo Gordo', pricePerKg: 12850, change: 150, changePercent: 1.18, unit: '₲/kg', updatedAt: new Date('2026-05-07') },
  { id: '2', category: 'Vaca Gorda', pricePerKg: 11200, change: -50, changePercent: -0.44, unit: '₲/kg', updatedAt: new Date('2026-05-07') },
  { id: '3', category: 'Vaquillona', pricePerKg: 11800, change: 200, changePercent: 1.72, unit: '₲/kg', updatedAt: new Date('2026-05-07') },
  { id: '4', category: 'Ternero', pricePerKg: 14500, change: 300, changePercent: 2.11, unit: '₲/kg', updatedAt: new Date('2026-05-07') },
  { id: '5', category: 'Ternera', pricePerKg: 13800, change: 100, changePercent: 0.73, unit: '₲/kg', updatedAt: new Date('2026-05-07') },
  { id: '6', category: 'Toro', pricePerKg: 10500, change: 0, changePercent: 0, unit: '₲/kg', updatedAt: new Date('2026-05-07') },
];

// Mock International Prices
export const mockInternationalPrices: InternationalPrice[] = [
  {
    id: '1',
    commodity: 'Soja',
    price: 385.50,
    unit: 'USD/ton',
    change: 4.25,
    changePercent: 1.11,
    market: 'CBOT Chicago',
    updatedAt: new Date('2026-05-07'),
  },
  {
    id: '2',
    commodity: 'Maiz',
    price: 178.30,
    unit: 'USD/ton',
    change: -2.10,
    changePercent: -1.16,
    market: 'CBOT Chicago',
    updatedAt: new Date('2026-05-07'),
  },
  {
    id: '3',
    commodity: 'Trigo',
    price: 245.80,
    unit: 'USD/ton',
    change: 3.50,
    changePercent: 1.44,
    market: 'CBOT Chicago',
    updatedAt: new Date('2026-05-07'),
  },
  {
    id: '4',
    commodity: 'Carne Bovina',
    price: 4250,
    unit: 'USD/ton',
    change: 75,
    changePercent: 1.79,
    market: 'USDA',
    updatedAt: new Date('2026-05-07'),
  },
  {
    id: '5',
    commodity: 'Aceite de Soja',
    price: 1085,
    unit: 'USD/ton',
    change: -15,
    changePercent: -1.36,
    market: 'CBOT Chicago',
    updatedAt: new Date('2026-05-07'),
  },
  {
    id: '6',
    commodity: 'Harina de Soja',
    price: 342.60,
    unit: 'USD/ton',
    change: 5.80,
    changePercent: 1.72,
    market: 'CBOT Chicago',
    updatedAt: new Date('2026-05-07'),
  },
];

export const mockMarketPrices: MarketPrice[] = [
  ...mockCattlePrices.map((item) => ({
    id: `cattle-${item.id}`,
    kind: 'cattle' as const,
    label: item.category,
    market: 'Mercado Villeta',
    currency: 'PYG' as const,
    unit: item.unit,
    value: item.pricePerKg,
    change: item.change,
    changePercent: item.changePercent,
    updatedAt: item.updatedAt,
  })),
  ...mockInternationalPrices.map((item) => ({
    id: `international-${item.id}`,
    kind: 'international' as const,
    label: item.commodity,
    market: item.market,
    currency: 'USD' as const,
    unit: item.unit,
    value: item.price,
    change: item.change,
    changePercent: item.changePercent,
    updatedAt: item.updatedAt,
  })),
];

// Mock Ecosystem Sites
export const mockEcosystemSites: EcosystemSite[] = [
  {
    id: '1',
    name: 'Eventosagropy',
    description: 'El primer y unico calendario digital del sector agropecuario paraguayo. Ferias, congresos, remates y eventos del agro en una sola plataforma.',
    url: 'https://eventosagropy.com',
    logoUrl: '/ecosystem/eventosagropy.png',
    category: 'eventos',
    tags: ['Calendario', 'Eventos', 'Ferias', 'Remates'],
  },
  {
    id: '2',
    name: 'Agrojuego',
    description: 'El primer juego educativo del sector agropecuario. Aprende sobre el agro de forma divertida y dinamica.',
    url: 'https://agrojuego.com',
    logoUrl: '/ecosystem/agrojuego.png',
    category: 'juegos',
    tags: ['Educacion', 'Juegos', 'Gamificacion', 'Interactivo'],
  },
  {
    id: '3',
    name: 'Agroconecta',
    description: 'Portal institucional del ecosistema digital agropecuario de Paraguay. Conoce todos nuestros productos y proyectos.',
    url: 'https://new.agroconecta.com.py',
    logoUrl: '/ecosystem/agroconecta.png',
    category: 'institucional',
    tags: ['Institucional', 'Ecosistema', 'Digital', 'Agro'],
  },
];

// Mock Institution News
export const mockInstitutionNews: InstitutionNews[] = [
  {
    id: '1',
    title: 'SENACSA actualiza protocolos de vacunacion contra aftosa',
    content: 'Nuevas directrices para la campana de vacunacion del segundo semestre 2026.',
    institution: 'SENACSA',
    institutionLogo: '/institutions/senacsa.png',
    publishedAt: new Date('2026-05-06'),
    type: 'comunicado',
  },
  {
    id: '2',
    title: 'MAG anuncia programa de creditos para pequenos productores',
    content: 'Lineas de financiamiento con tasas preferenciales disponibles desde junio.',
    institution: 'MAG',
    institutionLogo: '/institutions/mag.png',
    publishedAt: new Date('2026-05-05'),
    type: 'comunicado',
  },
  {
    id: '3',
    title: 'Resolucion N 245/2026: Nuevos requisitos para exportacion de granos',
    content: 'Se establecen nuevos parametros de calidad para embarques al exterior.',
    institution: 'SENAVE',
    institutionLogo: '/institutions/senave.png',
    publishedAt: new Date('2026-05-04'),
    type: 'resolucion',
  },
  {
    id: '4',
    title: 'Alerta fitosanitaria: Deteccion de roya asiatica en Itapua',
    content: 'Se recomienda monitoreo intensivo en lotes de soja de la region.',
    institution: 'SENAVE',
    institutionLogo: '/institutions/senave.png',
    publishedAt: new Date('2026-05-03'),
    type: 'alerta',
  },
];

// Mock Videos
export const mockVideos: VideoItem[] = [
  {
    id: 'a1',
    title: 'Remate Brangus Primavera 2026 - transmision en vivo',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=900',
    duration: 'En vivo',
    channel: 'Asociacion Paraguaya de Brangus',
    category: 'ganaderia',
    views: 3480,
    publishedAt: new Date('2026-05-07'),
    youtubeUrl: 'https://www.youtube.com/embed/live_stream?channel=UC_x5XG1OV2P6uZZ5FSM9Ttw',
    contentType: 'auction',
    auctionStatus: 'live',
    startsAt: new Date('2026-05-12T19:00:00-04:00'),
    organizationId: 'asociacion-brangus',
  },
  {
    id: 'v1',
    title: 'Mercado de Villeta: Precios del ganado en mayo 2026',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=600',
    duration: '8:24',
    channel: 'Agroconecta Medios',
    category: 'ganaderia',
    views: 12400,
    publishedAt: new Date('2026-05-06'),
  },
  {
    id: 'v2',
    title: 'Soja 2026: Perspectivas de la cosecha en el Este del pais',
    thumbnailUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600',
    duration: '12:10',
    channel: 'Poder Agropecuario',
    category: 'agricultura',
    views: 8750,
    publishedAt: new Date('2026-05-05'),
  },
  {
    id: 'v3',
    title: 'Clima y Agro: Temporada invernal, que esperar en el campo',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=600',
    duration: '5:45',
    channel: 'Campo Agropecuario',
    category: 'clima',
    views: 5320,
    publishedAt: new Date('2026-05-05'),
  },
  {
    id: 'v4',
    title: 'Tecnologia de precision: Drones en la agricultura paraguaya',
    thumbnailUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600',
    duration: '15:30',
    channel: 'ABC Rural',
    category: 'tecnologia',
    views: 21000,
    publishedAt: new Date('2026-05-04'),
  },
  {
    id: 'v5',
    title: 'SENACSA explica protocolo de exportacion a la Union Europea',
    thumbnailUrl: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600',
    duration: '9:15',
    channel: 'SENACSA Oficial',
    category: 'institucional',
    views: 6800,
    publishedAt: new Date('2026-05-04'),
  },
  {
    id: 'v6',
    title: 'Como funciona el mercado de futuros de soja en Chicago',
    thumbnailUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600',
    duration: '18:50',
    channel: 'Poder Agropecuario',
    category: 'mercados',
    views: 14200,
    publishedAt: new Date('2026-05-03'),
  },
  {
    id: 'v7',
    title: 'Ganaderia regenerativa: Experiencia de un productor del Chaco',
    thumbnailUrl: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=600',
    duration: '22:05',
    channel: 'Campo Agropecuario',
    category: 'ganaderia',
    views: 9300,
    publishedAt: new Date('2026-05-02'),
  },
  {
    id: 'v8',
    title: 'Trigo: Guia completa de preparacion para la siembra 2026',
    thumbnailUrl: 'https://images.unsplash.com/photo-1601472544834-5ec4b49d0a4c?w=600',
    duration: '11:40',
    channel: 'ABC Rural',
    category: 'agricultura',
    views: 7100,
    publishedAt: new Date('2026-05-02'),
  },
];

// Helper function to get category label
export function getCategoryLabel(category: NewsCategory): string {
  return newsCategories.find(c => c.value === category)?.label || category;
}

// Helper function to get department label
export function getDepartmentLabel(department: Department): string {
  return departments.find(d => d.value === department)?.label || department;
}

// Helper function to get profession label
export function getProfessionLabel(profession: Profession): string {
  return professions.find(p => p.value === profession)?.label || profession;
}
