import type { FeedContentType } from './types'

export const TYPE_LABEL: Record<FeedContentType, string> = {
  noticia: 'NOTICIA',
  video: 'VIDEO',
  evento: 'EVENTO',
  curso: 'CURSO',
  producto: 'PRODUCTO',
  servicio: 'SERVICIO',
  empleo: 'EMPLEO',
  remate: 'REMATE',
}

/** Tipos que usan el botón de acción: los de contenido + la tarjeta "Tu mercado hoy". */
export type CtaKind = FeedContentType | 'precios' | 'patrocinado'

// Texto del botón de acción estandarizado (README §3.1): mismo botón siempre, solo cambia esto.
export const CTA_LABEL: Record<CtaKind, string> = {
  noticia: 'Ver noticia',
  video: 'Ver video',
  evento: 'Ver evento',
  curso: 'Ver curso',
  producto: 'Ver producto',
  servicio: 'Ver servicio',
  empleo: 'Ver oportunidad',
  remate: 'Ver remate',
  precios: 'Ver todos los precios',
  patrocinado: 'Ver promoción',
}

/** El anunciante puede cargar su propio texto (máx. 18 caracteres, lo valida la base). */
export const CTA_MAX_LENGTH = 18

export const FEED_TEXT = {
  brand: 'Agroconecta',
  search: 'Buscar',
  like: 'Me gusta',
  save: 'Guardar',
  saved: 'Guardado',
  share: 'Enviar',
  shareA11y: 'Compartir',
  follow: 'Seguir',
  unfollow: 'Dejar de seguir',
  play: 'Reproducir video',
  live: 'EN VIVO',
  emptyTitle: 'Todavía no hay contenido',
  emptyBody: 'Deslizá hacia abajo para actualizar.',
  errorTitle: 'No pudimos cargar tu feed',
  errorBody: 'Revisá tu conexión y probá de nuevo.',
  retry: 'Reintentar',
  marketChip: 'MERCADO',
  marketTitle: 'Tu mercado hoy',
  marketUpdated: 'Actualizado',
  marketEmpty: 'Los precios no están disponibles en este momento.',
  refreshing: 'Actualizando…',
} as const

export const DETAIL_TEXT = {
  close: 'Cerrar',
  follow: 'Seguir',
  following: 'Siguiendo',
  remindOff: 'Activar recordatorio',
  remindOn: 'Recordatorio activado',
  watchLive: 'Ver transmisión en vivo',
  save: 'Guardar',
  saved: 'Guardado',
  share: 'Compartir',
  eventHub: 'Ver programa y noticias del evento',
  fullVideo: 'Ver video completo',
  contact: 'Contactar',
  toastRemindOn: 'Te avisamos 1 hora antes',
  toastRemindOff: 'Recordatorio desactivado',
  toastDenied: 'Activá las notificaciones en los ajustes del teléfono',
  toastSaved: 'Guardado en tu lista',
  toastUnsaved: 'Quitado de Guardados',
  toastError: 'No pudimos guardar el cambio. Probá de nuevo.',
} as const

export const PRICES_TEXT = {
  title: 'Mercado',
  back: 'Volver',
  share: 'Compartir precios',
  search: 'Buscar precios',
  clearSearch: 'Borrar búsqueda',
  cattle: 'Ganado',
  international: 'Internacional',
  featured: 'DESTACADO',
  updatedToday: 'Actualizado hoy',
  noUpdates: 'Sin actualizaciones',
  emptyTitle: 'Precios no disponibles',
  emptyBody: 'Todavía no hay precios cargados. Volvé a revisar más tarde.',
  noResults: 'No encontramos precios con esa búsqueda.',
  disclaimer: 'Valores de referencia. No constituyen una cotización oficial.',
  shareCattle: 'Precios de Ganado',
  shareInternational: 'Precios Internacionales',
} as const

export const EXPLORE_TEXT = {
  title: 'Explorar',
  search: 'Buscar en Agroconecta',
  clearSearch: 'Borrar búsqueda',
  categories: 'CATEGORÍAS',
  trending: 'TENDENCIAS',
  clear: 'Limpiar',
  resultsFor: 'Resultados para',
  noResults: 'No encontramos nada con eso. Probá con “soja”, “remate” o “curso”.',
  error: 'No pudimos cargar los resultados.',
  retry: 'Reintentar',
  pricesTitle: 'Precios de hoy',
  pricesBody: 'Ganado e internacionales',
  posts: (n: number) => (n === 1 ? '1 publicación' : `${n} publicaciones`),
} as const

export const RUBROS: { value: string; label: string }[] = [
  { value: 'agricultura', label: 'Agricultura' },
  { value: 'ganaderia', label: 'Ganadería' },
  { value: 'horticultura', label: 'Horticultura' },
  { value: 'tecnologia', label: 'Tecnología' },
  { value: 'mercados', label: 'Mercados' },
]

export const CATEGORY_LABEL: Record<FeedContentType, string> = {
  noticia: 'Noticias',
  evento: 'Eventos',
  video: 'Videos',
  curso: 'Cursos',
  producto: 'Productos',
  servicio: 'Servicios',
  empleo: 'Empleos',
  remate: 'Remates',
}

export const GUARDADOS_TEXT = {
  title: 'Guardados',
  tabSaved: 'Guardados',
  tabReminders: 'Recordatorios',
  tabActivity: 'Actividad',
  emptySavedTitle: 'Todavía no guardaste nada',
  emptySavedBody: 'Tocá el ícono de guardar en cualquier publicación del Inicio y la vas a encontrar acá.',
  emptyRemindersTitle: 'No tenés recordatorios',
  emptyRemindersBody: 'Abrí un evento o un remate y tocá "Activar recordatorio".',
  remindersNote: 'Te avisamos 1 hora antes.',
  activityNote: 'Tu actividad de los últimos 30 días.',
  activity: { viewed: 'Contenido visto', events: 'Eventos visitados', products: 'Productos consultados' },
  activityNone: 'Nada todavía',
  error: 'No pudimos cargar tus guardados.',
  retry: 'Reintentar',
  reminderSwitch: 'Recordatorio',
  guestTitle: 'Tus guardados, en un solo lugar',
  guestBody: 'Iniciá sesión para guardar noticias, eventos y cursos, activar recordatorios y ver tu actividad.',
} as const

export const PROFILE_TEXT = {
  edit: 'Editar perfil',
  more: 'Más opciones',
  completeCv: 'Completá tu perfil profesional',
  completeCvBody: 'Sumá tu cargo, formación y experiencia. Así te conocen el resto de los productores y profesionales.',
  completeCvCta: 'Completar perfil',
  about: 'Sobre mí',
  experience: 'Experiencia',
  specialties: 'Especialidades',
  education: 'Formación',
  organizations: 'Organizaciones que seguís',
  socials: 'Redes sociales',
  manageOrgs: 'Gestionar',
  noOrgs: 'Todavía no seguís a ninguna organización.',
  share: 'Compartir perfil',
  shareMessage: (name: string, url: string) => `Mirá el perfil de ${name} en Agroconecta${url ? `: ${url}` : ''}`,
  shareNeedsPublic: 'Activá "Perfil público" y elegí tu dirección para compartirlo.',
  followingCount: (n: number) => (n === 1 ? 'Seguís 1 organización.' : `Seguís ${n} organizaciones.`),
  socialLabel: { linkedin: 'LinkedIn', instagram: 'Instagram', facebook: 'Facebook', x: 'X', youtube: 'YouTube', website: 'Sitio web' },
  avatarTitle: 'Foto de perfil',
  avatarBody: 'Se guarda solo en este dispositivo.',
  avatarChange: 'Cambiar foto',
  avatarRemove: 'Quitar foto',
  cancel: 'Cancelar',
  guestTitle: 'Iniciá sesión',
  guestBody: 'Entrá con tu cuenta para guardar contenido, seguir organizaciones y armar tu perfil.',
  guestCta: 'Iniciar sesión',
} as const

export const MORE_TEXT = {
  title: 'Más',
  account: 'CUENTA',
  agroconecta: 'AGROCONECTA',
  legal: 'LEGAL',
  editCv: 'Editar perfil profesional',
  notifications: 'Notificaciones',
  following: 'Cuentas seguidas',
  library: 'Biblioteca',
  publish: 'Publicar',
  join: 'Sumate a Agroconecta',
  allies: 'Aliados',
  about: 'Nosotros',
  contact: 'Contacto',
  terms: 'Términos y condiciones',
  privacy: 'Política de privacidad',
  logout: 'Cerrar sesión',
  deleteAccount: 'Eliminar cuenta',
  logoutTitle: 'Cerrar sesión',
  logoutBody: '¿Seguro que querés salir de tu cuenta?',
  logoutConfirm: 'Salir',
  cancel: 'Cancelar',
} as const

export const EDIT_CV_TEXT = {
  title: 'Editar perfil',
  save: 'Guardar',
  saving: 'Guardando…',
  saved: 'Perfil actualizado',
  savedWithPoints: (pts: number) => `Perfil completo: sumaste ${pts} pts`,
  error: 'No pudimos guardar tu perfil. Probá de nuevo.',
  basics: 'Nombre, profesión y departamento',
  sectionPro: 'PERFIL PROFESIONAL',
  sectionExp: 'EXPERIENCIA',
  sectionSocial: 'REDES SOCIALES',
  headline: 'Cargo',
  headlineHint: 'Ej.: Ingeniero agrónomo',
  currentOrg: 'Dónde trabajás',
  currentOrgHint: 'Ej.: Cooperativa Colonias Unidas',
  education: 'Formación',
  educationHint: 'Ej.: Ing. Agronómica — UNA',
  country: 'País',
  bio: 'Sobre mí',
  bioHint: 'Contá en pocas líneas a qué te dedicás.',
  specialties: 'Especialidades',
  specialtiesHint: 'Separadas por coma: soja, manejo de suelos, drones',
  expRole: 'Cargo',
  expOrg: 'Empresa u organización',
  expPeriod: 'Período (ej.: 2019 – hoy)',
  expAdd: 'Agregar experiencia',
  expRemove: 'Quitar',
  socialHint: 'Usuario o enlace',
  sectionPublic: 'PERFIL PÚBLICO',
  publicToggle: 'Cualquiera con el enlace puede ver mi perfil',
  slug: 'Tu dirección',
  slugHint: 'ej.: juan-perez',
  slugTaken: 'Esa dirección ya está en uso. Probá con otra.',
  slugInvalid: 'La dirección tiene que tener entre 3 y 40 letras, números o guiones.',
  back: 'Volver',
} as const

export const POINTS_TEXT = {
  pts: (n: number) => `${n.toLocaleString('es-PY')} pts`,
  earned: (n: number) => `+${n} pts ganados`,
  plus: (n: number) => `+${n} pts`,
  pillA11y: (n: number) => `Mis puntos: ${n}`,
  cardTitle: 'Puntos Agroconecta',
  cardBody: 'Encuestas y quizzes suman puntos',
  redeem: 'Canjear',
  toastEarned: (n: number) => `¡Listo! +${n} puntos`,
  notVerified: 'Verificá tu email para sumar puntos',
} as const

export const POLL_TEXT = {
  label: 'ENCUESTA',
  tapToVote: 'Tocá una opción para votar',
  votes: (n: number) => `${n.toLocaleString('es-PY')} votos · Gracias por participar`,
  error: 'No pudimos registrar tu voto. Probá de nuevo.',
} as const

export const QUIZ_TEXT = {
  label: 'QUIZ AGRO',
  step: (i: number, total: number) => `${i} DE ${total}`,
  complete: 'COMPLETO',
  perCorrect: (n: number) => `+${n} pts por acierto`,
  correct: 'Correcta',
  yours: 'Tu respuesta',
  next: 'Siguiente pregunta',
  result: 'Ver resultado',
  score: (ok: number, total: number) => `${ok} de ${total} correctas`,
  earned: (pts: number) => `Sumaste ${pts} puntos a tu perfil`,
  none: 'Esta vez no sumaste, ¡mañana hay otro quiz!',
  toastWrong: 'Casi. Te marcamos la correcta',
  redeem: 'Ver qué puedo canjear',
  error: 'No pudimos registrar tu respuesta. Probá de nuevo.',
} as const

export const ONBOARDING_TEXT = {
  next: 'Siguiente',
  skip: 'Saltar',
  back: 'Volver',
  finish: 'Empezar a usar Agroconecta',
  start: 'Empezar',
  stepOf: (step: number, total: number) => `Paso ${step} de ${total}`,
  finishing: 'Preparando tu feed…',
  welcomeTitle: 'Bienvenido a Agroconecta',
  welcomeBody: 'El feed del agro paraguayo, hecho a tu medida.',
  welcomeItems: [
    { icon: 'phone-portrait-outline', title: 'Un contenido por pantalla', body: 'Deslizá hacia arriba: noticias, remates, cursos y más.' },
    { icon: 'sparkles-outline', title: 'Karai te responde', body: 'Preguntale lo que necesites saber del agro.' },
    { icon: 'star-outline', title: 'Sumá puntos', body: 'Respondé encuestas y quizzes y canjealos por cursos y eventos.' },
  ],
  nameTitle: '¿Cómo te llamás?',
  nameLabel: 'Nombre y apellido',
  rubrosTitle: '¿En qué rubros estás?',
  rubrosBody: 'Elegí uno o más. Así tu feed arranca con lo que te importa.',
  productionTitle: '¿Qué producís o te interesa?',
  productionBody: 'Opcional. Nos ayuda a mostrarte lo más relevante.',
  professionTitle: '¿A qué te dedicás?',
  scaleTitle: '¿Cómo te describís mejor?',
  scaleBody: 'Opcional.',
  departmentTitle: '¿En qué departamento estás?',
  departmentBody: 'Para mostrarte eventos y noticias cercanas.',
  goalsTitle: '¿Para qué usás Agroconecta?',
  goalsBody: 'Elegí todo lo que aplique.',
  orgsTitle: 'Seguí a quienes te interesan',
  orgsBody: 'Te recomendamos seguir al menos 3 organizaciones o medios.',
  notifTitle: 'Enterate a tiempo',
  notifBody: 'Te avisamos cuando empieza un remate que seguís, sale una noticia importante o cambian los precios.',
  notifCta: 'Activar notificaciones',
  notifOn: 'Notificaciones activadas',
  notifCategories: { breakingNews: 'Noticias importantes', priceAlerts: 'Alertas de precios', weatherAlerts: 'Alertas de clima', institutionalUpdates: 'Novedades institucionales' },
  phoneTitle: 'Tu WhatsApp',
  phoneBody: 'Opcional. Más adelante vas a poder recibir alertas y hablar con Karai por WhatsApp.',
  phoneLabel: 'Número de WhatsApp',
  consentTitle: 'Último paso',
  consentTerms: 'Acepto los términos y condiciones y la política de privacidad.',
  consentPoints: 'Quiero participar del programa de puntos. Soy mayor de 18 años, vivo en Paraguay y acepto su reglamento.',
  readTerms: 'Leer términos',
  readPrivacy: 'Leer privacidad',
  readRules: 'Leer reglamento',
} as const

export const KARAI_TEXT = {
  name: 'Karai',
  title: '¿Qué necesitás saber del agro?',
  newChat: 'Nueva consulta',
  suggestions: ['¿Qué pasó hoy en el agro?', 'Eventos esta semana', 'Mostrame cursos disponibles', 'Noticias sobre ganadería'],
  placeholder: 'Preguntale a Karai…',
  send: 'Enviar',
  typing: 'Karai está escribiendo',
  campoEyebrow: 'KARAI CAMPO',
  campoTitle: 'Administrá tu establecimiento con ayuda de inteligencia artificial.',
  campoCta: 'Conocer KARAI Campo',
  campoExcerpt: 'Interés en KARAI Campo (desde la app)',
  campoThanks: '¡Listo! Te avisamos cuando KARAI Campo esté disponible.',
  quota: (left: number) => (left === 1 ? 'Te queda 1 consulta hoy' : `Te quedan ${left} consultas hoy`),
  error: 'No pudimos conectar con Karai. Probá de nuevo en un momento.',
  membersOnlyCta: 'Ver cómo sumarme',
  guestTitle: 'Preguntale a Karai',
  guestBody: 'Iniciá sesión para consultar precios, eventos y todo lo que necesites saber del agro.',
} as const

export const AD_TEXT = {
  chip: 'PATROCINADO',
  defaultCta: 'Ver promoción',
  why: '¿Por qué lo veo?',
  whyTitle: 'Publicidad',
  whyBody: 'Ves este anuncio porque coincide con tu profesión, tu departamento o tus intereses. Los anuncios siempre están marcados como "Patrocinado".',
  whyOk: 'Entendido',
  hide: 'No me interesa',
  hidden: 'No vas a ver más este anuncio',
  pautar: '¿Querés pautar tu contenido acá?',
  learnMore: 'Conocer más',
  leadLabel: 'Publicidad en Agroconecta',
  leadTitle: 'Pautá en Agroconecta',
  leadBody: 'Llegá a productores, técnicos y empresas del agro paraguayo con contenido en el feed y dentro de las noticias. Dejanos tu contacto y te escribimos.',
  back: 'Volver',
} as const

export const LIVE_TEXT = {
  chip: 'EN VIVO',
  now: 'EN VIVO AHORA',
  watch: 'Ver en vivo',
  notInterested: 'No me interesa',
  close: 'Cerrar aviso',
  expand: 'Ver más del aviso',
  collapse: 'Plegar aviso',
  see: 'Ver',
  showHome: 'Mostrar en Inicio',
} as const

export const REWARDS_TEXT = {
  title: 'Canjear puntos',
  back: 'Volver',
  balance: 'Tu saldo',
  nextGoal: (missing: number, title: string) => `Te faltan ${missing.toLocaleString('es-PY')} pts para: ${title}`,
  allUnlocked: 'Podés canjear todo el catálogo',
  catalog: 'CURSOS Y EVENTOS',
  mine: 'MIS CANJES',
  howTo: 'CÓMO SUMAR PUNTOS',
  history: 'HISTORIAL',
  redeem: 'Canjear',
  missing: (n: number) => `Faltan ${n.toLocaleString('es-PY')}`,
  outOfStock: 'Sin cupos',
  confirmTitle: 'Confirmar canje',
  confirmBody: (title: string, cost: number) => `Vas a usar ${cost.toLocaleString('es-PY')} pts en "${title}".`,
  confirm: 'Canjear',
  cancel: 'Cancelar',
  done: (code: string) => `¡Listo! Tu código es ${code}`,
  copied: 'Código copiado',
  copy: 'Copiar código',
  errors: {
    unavailable: 'Este premio ya no está disponible.',
    out_of_stock: 'Se agotaron los cupos de este premio.',
    insufficient: 'Todavía no te alcanzan los puntos.',
    network: 'No pudimos hacer el canje. Probá de nuevo.',
  },
  status: { emitido: 'Para usar', usado: 'Usado', vencido: 'Vencido', anulado: 'Anulado' },
  expires: (date: string) => `Vence el ${date}`,
  rules: 'Ver reglamento de puntos',
  rulesNote: 'Los puntos vencen si pasan 12 meses sin que sumes ni canjees, y cada código vale 60 días.',
  kind: { curso: 'CURSO', evento: 'EVENTO', charla: 'CHARLA' },
  emptyCatalog: 'Pronto vas a poder canjear tus puntos por cursos y entradas a eventos de nuestros aliados.',
  emptyMine: 'Todavía no canjeaste nada.',
  emptyHistory: 'Todavía no tenés movimientos.',
  ways: ['Respondé la encuesta del día: +10 pts', 'Acertá en los quizzes: +10 pts por respuesta', 'Completá tu perfil profesional: +30 pts'],
} as const

/** 1284 → "1.284"; 12400 → "12,4 mil" (mismo formato que el prototipo). */
export function formatCount(n: number): string {
  if (n >= 10_000) return `${(n / 1000).toFixed(1).replace('.', ',')} mil`
  return n.toLocaleString('es-PY')
}
